data <- read.csv('household_power_consumption.txt', na.strings='?', sep=';')
selection <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
selection$DateTime <- strptime(with(selection, paste(Date, Time, sep="-")), "%d/%m/%Y-%H:%M:%S")
par(mfrow=c(2,2))
plot(selection$DateTime, selection$Global_active_power, ylab="Global Active Power", xlab="", type='l')
plot(selection$DateTime, selection$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(selection$DateTime, selection$Sub_metering_1, type='l', xlab="", ylab="Energy sub metering")
lines(selection$DateTime, selection$Sub_metering_2, col='red')
lines(selection$DateTime, selection$Sub_metering_3, col='blue')
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
plot(selection$DateTime, selection$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, "plot4.png")
dev.off()